filter:
    excluded_paths:
        - 'vendor/*'

tools:
    php_mess_detector:
        config:
            controversial_rules: { superglobals: false }
            design_rules: { coupling_between_objects: 15 }
    php_cpd: true
    php_pdepend: true
    php_code_coverage: false
    php_code_sniffer: true
    php_cs_fixer: true
    php_loc: true
    php_analyzer: true
    sensiolabs_security_checker: true
    external_code_coverage:
        timeout: 1800 # Timeout in seconds

checks:
    php:
        code_rating: true
        duplication: true
        sql_injection_vulnerabilities: true
        security_vulnerabilities: true
        no_eval: true
