<div class="smw-factedsearch {{theme}}">
 <div class="smw-factedsearch-search">{{search}}</div>{{search-extra-fields}}
  <div class="smw-factedsearch-container">
   <div class="smw-factedsearch-sidebar">{{sidebar}}</div>
   <div class="smw-factedsearch-content is-disabled-not">{{content}}
    <div id="smw-factedsearch-content-overlay" class="smw-overlay-spinner-not large inline"></div>
   </div>
  </div>
 </div>
</div>