<?php

namespace SMW\MediaWiki\Specials\Admin;

use SMW\ApplicationFactory;
use SMW\MediaWiki\Renderer\HtmlFormRenderer;
use Onoi\MessageReporter\MessageReporterFactory;
use SMW\SQLStore\Installer;
use SMW\Message;
use SMW\Store;
use Html;
use WebRequest;

/**
 * @license GNU GPL v2+
 * @since   2.5
 *
 * @author mwjames
 */
class TableSchemaUpdaterSection {

	/**
	 * @var Store
	 */
	private $store;

	/**
	 * @var HtmlFormRenderer
	 */
	private $htmlFormRenderer;

	/**
	 * @var boolean
	 */
	private $enabledSetupStore = false;

	/**
	 * @var OutputFormatter
	 */
	private $outputFormatter;

	/**
	 * @since 2.5
	 *
	 * @param Store $store
	 * @param HtmlFormRenderer $htmlFormRenderer
	 * @param OutputFormatter $outputFormatter
	 */
	public function __construct( Store $store, HtmlFormRenderer $htmlFormRenderer, OutputFormatter $outputFormatter ) {
		$this->store = $store;
		$this->htmlFormRenderer = $htmlFormRenderer;
		$this->outputFormatter = $outputFormatter;
	}

	/**
	 * @since 2.5
	 *
	 * @param boolean $enabledSetupStore
	 */
	public function enabledSetupStore( $enabledSetupStore ) {
		$this->enabledSetupStore = (bool)$enabledSetupStore;
	}

	/**
	 * @since 2.5
	 *
	 * @return string
	 */
	public function getForm() {

		$this->htmlFormRenderer
			->setName( 'buildtables' )
			->setMethod( 'get' )
			->addHiddenField( 'action', 'updatetables' )
			->addHeader( 'h2', $this->getMessage( 'smw_smwadmin_db' ) );

		if ( $this->enabledSetupStore ) {
			$this->htmlFormRenderer
				->addParagraph( $this->getMessage( 'smw_smwadmin_dbdocu' ) )
				->addHiddenField( 'udsure', 'yes' )
				->addSubmitButton( $this->getMessage( 'smw_smwadmin_dbbutton' ) );
		} else {
			$this->htmlFormRenderer
				->addParagraph( $this->getMessage( 'smw-smwadmin-dbsetup-disabled' ) );
		}

		return $this->htmlFormRenderer->getForm() . Html::element( 'p', array(), '' );
	}

	/**
	 * @since 2.5
	 *
	 * @param WebRequest $webRequest
	 *
	 * @return callable
	 */
	public function doUpdate( WebRequest $webRequest ) {

		if ( !$this->enabledSetupStore ) {
			return;
		}

		$messageReporter = MessageReporterFactory::getInstance()->newObservableMessageReporter();
		$messageReporter->registerReporterCallback( array( $this, 'reportMessage' ) );

		$this->outputFormatter->setPageTitle( $this->getMessage( 'smw_smwadmin_db' ) );
		$this->outputFormatter->addParentLink();

		$this->store->getOptions()->set( Installer::OPT_MESSAGEREPORTER, $messageReporter );

		$this->outputFormatter->addHTML( Html::rawElement( 'p', array(), $this->getMessage( 'smw_smwadmin_permissionswarn' ) ) );

		$this->outputFormatter->addHTML( '<pre>' );

		// Output is generated by the injected 'installer.messagereporter'
		$result = $this->store->setup();

		$this->outputFormatter->addHTML( '</pre>' );

		if ( $result === true && $webRequest->getText( 'udsure' ) == 'yes' ) {
			$this->outputFormatter->addWikiText( '<p><b>' . $this->getMessage( 'smw_smwadmin_setupsuccess' ) . "</b></p>" );
		}
	}

	/**
	 * @since 2.5
	 *
	 * @param string $message
	 */
	public function reportMessage( $message ) {
		$this->outputFormatter->addHTML( $message );
	}

	private function getMessage( $key, $type = Message::TEXT ) {
		return Message::get( $key, $type, Message::USER_LANGUAGE );
	}

}
